#data configs

#tokenize
#input_jsonl: ../../data/text/corpus_scale_200.jsonl
#output_prefix: ../../data/text/0420test

#train
tokenized_data_path: /storage5/split/split/split/tokenized_text_document
megatron_deepspeed_dir: Megatron-DeepSpeed
input_tokenizer_file: /storage5/split/split/split/tokernizer/tokenizer_scale200.model
output_model_dir: /storage5/checkpoints/7b_no_rope_master_BTM
save_interval: 1500
save_interval: 3000
#save_interval: 1000


# GPT-3 6.7B 1 node
model_size: 6.7
num_layers: 32
hidden_size: 4096
num_attn_heads: 32
global_batch_size: 32
lr: 1.2e-4
min_lr: 1.0e-6
init_std: 0.009
seq_len: 2048
NHOSTS: 1
activation_checkpoint: false


#deepspeed
zero_stage: 1

#token info
#train_tokens: 144112147
train_tokens: 195537374076 
lr_decay_tokens_in_billion: 193
lr_decay_tokens: 193537374076
#この値をきちんと決めておかないと、learning rateのスケジュラーがきちんと動かない
train_samples: 300000000 # 300B相当｡ もっと学習させる場合は大きくすること!!

#train_samples=$(( 300 * 1000 * 1000 * 1000 * 2 / ${seq_len} ))

num_workers: 16
mp_size: 1
pp_size: 1
sp_size: 1
