input_model_dir: /storage5/checkpoints/0501llama/checkpoint/gpt_8B_tok300B_lr2e-05_min2e-06_w2000M_d193B_cosine_gbs1536_mbs3_g24_z1_pp3_seed1234_rebase/global_step6300
output_tokenizer_and_model_dir: ../../models/hf/llama6300
temp_dir: /storage5/checkpoints/temp
huggingface_name: test
test_prompt_text: こんにちは､